name = "bts-fan"
compatibility_date = "2025-05-01"
compatibility_flags = [ "nodejs_compat" ]
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[placement]
mode = "smart"
