name = "bts"
type = "javascript"
account_id = "3ee7ad0ab483fdf2ab7ee7be24ddf365"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-04-07"

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = ""
upload.format = "service-worker"
